# Generated by Django 5.0.1 on 2024-01-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0002_kart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kart',
            name='kart_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kart_item',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kart.kart'),
        ),
    ]
