# Generated by Django 5.0.1 on 2024-05-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kart', '0004_alter_kart_item_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
