# Generated by Django 5.0 on 2024-01-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variations_options_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'ProductGallery', 'verbose_name_plural': 'ProductGalleries'},
        ),
    ]
