# Generated by Django 5.0.1 on 2024-01-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productgallery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='variation_category',
            field=models.CharField(choices=[('colors', 'colors'), ('sizes', 'sizes')], max_length=100),
        ),
    ]
