# Generated by Django 4.2.4 on 2023-10-18 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_productgallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
