# Generated by Django 4.2.4 on 2023-10-16 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='adddress_line_2',
            new_name='address_line_2',
        ),
    ]
