# Generated by Django 4.2.4 on 2023-09-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_creted_date_variation_created_date'),
        ('cartt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(null=True, to='store.variation'),
        ),
    ]
